### ISSUE TITLE
Boolean settings are now available

### ISSUE THREAD

**Issue by pieroit** [sambarza/cc-vscode-debugpy#1]
https://github.com/sambarza/cc-vscode-debugpy/blob/2de2095b33ed9fc784e896b15853afc88c15d423/vcc-vscode-debugpy.py#L15

You can now have settings like:

```python

class MyEnum(Enum):
        nic: str = 'Nicola'
        ema: str = 'Emanuele'
        pie: str = 'Piero'

class DemoSettings(BaseModel):
        required_int: int
        optional_int: int = 42
        required_str: str
        optional_str: str = "stocats"
        required_bool: bool
        optional_bool_true: bool = True
        required_date: date
        optional_date: date = date(2020, 11, 2)
        required_time: time
        optional_time: time = time(4, 12, 54)
        required_enum: MyEnum
        optional_enum: MyEnum = MyEnum.ema

```

**Comment by sambarza** [comment]
Now I'm using "bool" and I can see the checkbox:
![image](https://github.com/sambarza/cc-vscode-debugpy/assets/3630051/6b70f385-af9a-48f2-9589-533d2609577e)

But the bool setting is not save, seems not passed into the payload (others settings types like str are passed):
![image](https://github.com/sambarza/cc-vscode-debugpy/assets/3630051/b9695628-9817-4a0a-993d-664166529d89)

If not already known I can open an issue in the admin-vue repo.

**Comment by sambarza** [comment]
Something changed from my side, today no problem anymore, not investigated yet, checkbox setting looks good thanks!
